spring:
  jackson:
    default-property-inclusion: non_null

server:
  servlet:
    context-path: /tgp
  tomcat:
    accessLog.enabled: true
    basedir: "${LOG_PATH}/Application"
    accessLogPattern: "%h %l %u %t \"%r\" %s %b %D"


